services:
  server: 
    build: .
    env_file:
      - .env
    ports:
      - "${TODO_PORT:-7540}:${TODO_PORT:-7540}"
    volumes:
      - type: bind
        source: ./scheduler.db
        target: /usr/src/app/scheduler.db